/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.codesoom.assignment;

<<<<<<< HEAD
import com.sun.net.httpserver.HttpHandler;
import com.sun.net.httpserver.HttpServer;

import java.io.IOException;
import java.net.InetSocketAddress;

=======
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
>>>>>>> e7cf222 (Spring Web)
public class
App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
<<<<<<< HEAD
        System.out.println(new App().getGreeting());

        try {
            InetSocketAddress address = new InetSocketAddress(8000);
            HttpServer httpServer = HttpServer.create(address, 0);

            HttpHandler handler = new DemoHttpHandler();
            httpServer.createContext("/", handler);
            httpServer.start();
        } catch (IOException e) {
            e.printStackTrace();
        }
=======
        SpringApplication.run(App.class, args);
>>>>>>> e7cf222 (Spring Web)
    }
}
